apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: codewithdan-docker-services
build:
  artifacts:
  - image: sandeepkumarmohanty/nginx
    context: .
    docker:
      dockerfile: .docker/nginx.production.dockerfile
  - image: sandeepkumarmohanty/my-website
    context: .
    docker:
      dockerfile: .docker/node-codewithdan.production.dockerfile
  - image: sandeepkumarmohanty/mongo
    context: .
    docker:
      dockerfile: .docker/mongo.dockerfile
  - image: sandeepkumarmohanty/redis
    context: .
    docker:
      dockerfile: .docker/redis.production.dockerfile
deploy:
  kubectl:
    manifests:
    - .k8s/*.yml